export const officeSupplies = [
  {
    id: "1",
    name: "Maped Color Pencils",
    description: "Set of 12 colored pencils",
    price: 12.99,
  },
  {
    id: "2",
    name: "Sharpie Permanent Markers",
    description: "Set of 8 black markers",
    price: 9.99,
  },
  {
    id: "3",
    name: "Staples Easy Button",
    description: 'Press to hear "That was easy!"',
    price: 4.99,
  },
  {
    id: "4",
    name: "Scotch Tape",
    description: 'Transparent tape, 3/4" x 1000"',
    price: 2.49,
  },
  {
    id: "5",
    name: "Post-it Notes",
    description: '3" x 3" square, 100 sheets',
    price: 1.99,
  },
  {
    id: "6",
    name: "Composition Notebook",
    description: "100 sheets, college ruled",
    price: 2.99,
  },
  {
    id: "7",
    name: "Binder Clips",
    description: "Assorted sizes, 50 clips",
    price: 3.99,
  },
  {
    id: "8",
    name: "Whiteboard Markers",
    description: "Set of 4, black, red, blue, green",
    price: 5.99,
  },
  {
    id: "9",
    name: "Desk Organizer",
    description: "Mesh, 5 compartments",
    price: 12.99,
  },
  {
    id: "10",
    name: "Paper Clips",
    description: "Assorted colors, 1000 clips",
    price: 1.99,
  },
  {
    id: "11",
    name: "Desk Lamp",
    description: "LED, adjustable, black",
    price: 24.99,
  },
  {
    id: "12",
    name: "Dry Erase Board",
    description: '12" x 18", with marker and eraser',
    price: 14.99,
  },
  {
    id: "13",
    name: "File Folders",
    description: "Assorted colors, 12 folders",
    price: 5.99,
  },
  {
    id: "14",
    name: "Calculator",
    description: "Basic, solar powered",
    price: 6.99,
  },
  {
    id: "15",
    name: "Highlighters",
    description: "Set of 5, assorted colors",
    price: 4.99,
  },
  {
    id: "16",
    name: "Binder",
    description: '1" capacity, black',
    price: 3.99,
  },
  {
    id: "17",
    name: "Stapler",
    description: "Full strip, black",
    price: 7.99,
  },
  {
    id: "18",
    name: "Correction Tape",
    description: "2-pack, white",
    price: 3.49,
  },
  {
    id: "19",
    name: "Hole Punch",
    description: "3-hole, adjustable",
    price: 6.99,
  },
  {
    id: "20",
    name: "Mouse Pad",
    description: "Non-slip, black",
    price: 2,
  },
];
